apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard1
spec:
  serviceName: "mongo-shard1"
  replicas: 3
  selector:
    matchLabels:
      role: mongo-shard1
  template:
    metadata:
      labels:
        role: mongo-shard1
    spec:
      containers:
        - name: mongod
          image: mongo:6.0
          command:
            - "mongod"
            - "--shardsvr"
            - "--replSet"
            - "rsShard1"
            - "--port"
            - "27018"
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: mongo-shard1-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-shard1-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
