apiVersion: v1
kind: ServiceAccount
metadata:
  name: phototheque-admin-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: phototheque-admin-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phototheque-admin-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: phototheque-admin-sa
    namespace: default
roleRef:
  kind: Role
  name: phototheque-admin-role
  apiGroup: rbac.authorization.k8s.io

# kubectl apply -f rbac-auto-refresh.yml
# kubectl apply -f cronjob-auto-refresh.yml
