apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard1
spec:
  serviceName: "shard1"
  replicas: 1
  selector:
    matchLabels:
      app: shard1
  template:
    metadata:
      labels:
        app: shard1
    spec:
      containers:
      - name: shard1
        image: mongo:6.0
        command:
          - mongod
          - "--shardsvr"
          - "--replSet"
          - "shard1ReplSet"
          - "--port"
          - "27018"
          - "--bind_ip_all"
        ports:
        - containerPort: 27018
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
